import type { Metadata } from "next";
import { Carme, Zilla_Slab } from "next/font/google";
import "./globals.css";

export const carme = Carme({ subsets: ["latin"], weight: ["400"] });
const zilla = Zilla_Slab({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type ChildrenProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<ChildrenProps>) {
  return (
    <html lang="en">
      <body className={`${zilla.className} antialiased`}>{children}</body>
    </html>
  );
}
