import type { Metadata } from "next";
import "./globals.css";
import { zilla } from "@/lib/fonts";
import { Slide, ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type ChildrenProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<ChildrenProps>) {
  return (
    <html lang="en">
      <body className={`${zilla.className} antialiased`}>
        <ToastContainer />;{children}
      </body>
    </html>
  );
}
